@startmindmap
* HTTP协议 
**_ 使用TCP作为它的支撑运输协议
**_ 无状态协议
**_ 支持持续性连接和非持续性连接
***_ 持续性连接 每次请求都创建一个新的TCP连接，获取响应之后关闭该连接
***_ 非持续性连接 服务器在发送响应后保持该TCP连接打开
**_: 
                        报文格式
https://www.runoob.com/http/http-messages.html
;

***_ 请求 
****_: 
GET /somedir/page ・html HTTP/1.1    
Host: www someschool.edu
Connection: close
User-agent: Mozilla/5•0
Accept-language: fr;

***_ 响应 
****_: 
HTTP/1.1 200 OK
Connection: close
Date: Tue, 18 Aug 2015 15:44:04 GMT
Server: Apache/2.2.3 (CentOS)
Last-Modified: Tuer 18 Aug 2015 15:11:03 GMT
Content-Length: 6821
Content-Type: text/html
(data data data data data •••);

**_ cookie
***_: 
①在HTTP响应报文中的一个cookie首部行；
②在HTTP请求报文中的一个cookie首部行；
③在用户端系统中保留有一个cookie文件，并由用户的浏览器进行管理；
④位于Web站点的一个后端数据库;

**_ web缓存(代理服务器)
***_: 
①浏览器先与代理服务器TCP，并向web缓存器中的对象发送一个HTTP请求
②web缓存器检查，看看本地是否存储了该对象的副本，如果有那么直接返回
③如果没有就打开web缓存器与初始服务器的TCP连接，发送该对象的HTTP请求报文，初始服务器发送HTTP响应
④web缓存器存储响应副本，并向客户端浏览器发送HTTP响应;

**_ 条件GET方法
***_: 
①请求报文使用GET方法；
②请求报文中包含一个“If Modified-Since”;

@endmindmap